### ISSUE TITLE
Changes in BertForQuestionAnswering 

### ISSUE THREAD

**Issue by brunocosouza** [dredwardhyde/bert-examples#1]
Issues on **bert_squad_pytorch.py** file

When you infer the BertForQuestionAnswering object the variable *loss* returned is a *string type*.
Since one of the recent updates, the models return now task-specific output objects (which are dictionaries) instead of plain tuples

Solutions : call the *values()* method or assign False to *return_dict*

loss, _, _ = model(**inputs).values()
loss, _, _= model(**inputs, return_dict=False)

**Comment by dredwardhyde** [comment]
Thank you, I've updated all pytorch examples!
